### PR TITLE
Manually manage state in Attributes Table

### PR DESCRIPTION
**Pull request by wwqrd**
Due to the way redux-form manages it's state, empty fields in AttributesTable were being unmounted and lost. I think this comes down to an issue of using redux-form to drive dynamic forms, where the <Field /> components are actually generated reciprocally from the state.

This PR manages the AttributesTable value in component state, before calling redux-form's change()
method to update. It also introduces a DetachedField component which mirrors the one provided by
Redux Form, but doesn't connect to the redux state.

An alternative implementation might be to manage the variable references in component state, and
keep the values in redux-form, but that seems equally complicated if not more so.

Fixes: #275, #264

### CODE REVIEW

**Comment by rebeccamadsen** [comment]
This helps with not removing an attribute. It makes me wonder what other forms we're using are funky in this way...but I guess in NC we don't have dynamic forms.

Should the validation rules for additional attributes be satisfied before you can save? I noticed that some additional attributes, the value was "required", but I could save anyway. Or on age, the value should be less than 100, but I could put 222.

Also, should boolean values default to true? I'm seeing false here.

**Comment by wwqrd** [comment]
Ugh, not happy with this fix, but couldn't find a way around it.

We leverage Redux Forms for error handling on submit, so I've somewhat reinstated using additionalAttributes using Field (We used to use it for every input, now the entire table is treated as a single field). Field level validations are handled normally, with the emulated Field component (DetachedField), and form level validation is handled by performing one big validation on attributes table.

**Comment by wwqrd** [comment]
Known issues:
- [ ] When field is closed for editing, can't see validation errors
- [ ] When multiple errors are contained in the attributes table, only one is shown in the issues panel

**Comment by rebeccamadsen** [comment]
Looks good to me!

**Pull request merged**
