### PR TITLE
Editor for node types

### LINKED ISSUE #12: View for editing the variable registry

### PR DESCRIPTION
**Pull request by wwqrd**
screenshot

Partially resolves #12 

## Changes

- Adds a "variable registry" screen which can be accessed by clicking any of the nodes/edges on the overview panel at the top of a protocol.
- From this variable registry screen individual node/edge types can be edited, including editing any variables associated with each type.

## Known issues

- Unsure of best way to animate to/from these screens - "zoom" doesn't seem like the right fit.
- "type" name can't be edited.
- Possible misunderstanding of ordinal/categorical variable types: are options validations appropriate?
- **This feature is somewhat useless without the form editor. As although we can create node types, we can't populate them with a NameGenerator interface until we have a corresponding form. A Form Editor is the next feature.**

### CODE REVIEW

**Comment by rebeccamadsen** [comment]
I can edit protocol variables in my copy of the demo protocol, which is cool. I can then see these changes in NC after loading the protocol in Server, which is even more awesome. Some things I noticed, though maybe you already know these things.

I'm not sure what is expected, but "Create New Node Type" and "Create New Edge Type" lead to a blank screen with a "Cancel" button.

If I edit the registry variables and then go back to the main page, I don't get a choice to "save" my protocol. I have to change one of the stages somehow to be able to save the protocol.

Creating a new protocol and then attempting to edit the registry gives me a blank screen and these errors, with no option to "cancel". Reload wasn't helping me much, I had to close the app and restart:

```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at VariableRegistry._this.renderEdge (VariableRegistry.js:50)
    at lodash.js:3563
    at lodash.js:4925
    at baseForOwn (lodash.js:3010)
    at lodash.js:4894
    at baseMap (lodash.js:3562)
    at map (lodash.js:9554)
    at VariableRegistry.renderEdges (VariableRegistry.js:77)
    at VariableRegistry.render (VariableRegistry.js:143)
    at finishClassComponent (react-dom.development.js:13193)
    at updateClassComponent (react-dom.development.js:13155)
    at beginWork (react-dom.development.js:13824)
    at performUnitOfWork (react-dom.development.js:15863)
    at workLoop (react-dom.development.js:15902)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at replayUnitOfWork (react-dom.development.js:15310)
    at renderRoot (react-dom.development.js:15962)
    at performWorkOnRoot (react-dom.development.js:16560)
    at performWork (react-dom.development.js:16482)
    at performSyncWork (react-dom.development.js:16454)
    at interactiveUpdates$1 (react-dom.development.js:16719)
    at interactiveUpdates (react-dom.development.js:2150)
    at dispatchInteractiveEvent (react-dom.development.js:4532)
VariableRegistry._this.renderEdge @ VariableRegistry.js:50
(anonymous) @ lodash.js:3563
(anonymous) @ lodash.js:4925
baseForOwn @ lodash.js:3010
(anonymous) @ lodash.js:4894
baseMap @ lodash.js:3562
map @ lodash.js:9554
renderEdges @ VariableRegistry.js:77
render @ VariableRegistry.js:143
finishClassComponent @ react-dom.development.js:13193
updateClassComponent @ react-dom.development.js:13155
beginWork @ react-dom.development.js:13824
performUnitOfWork @ react-dom.development.js:15863
workLoop @ react-dom.development.js:15902
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
replayUnitOfWork @ react-dom.development.js:15310
renderRoot @ react-dom.development.js:15962
performWorkOnRoot @ react-dom.development.js:16560
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
interactiveUpdates$1 @ react-dom.development.js:16719
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4532
index.js:1 The above error occurred in the <VariableRegistry> component:
    in VariableRegistry (created by Connect(VariableRegistry))
    in Connect(VariableRegistry) (at ShowRoute.js:9)
    in Route (at ShowRoute.js:8)
    in ShowRoute (at Protocol.js:182)
    in div (at Protocol.js:138)
    in Protocol (created by Connect(Protocol))
    in Connect(Protocol) (at ViewTransitionRoute.js:19)
    in Transition (created by CSSTransition)
    in CSSTransition (at ViewTransitionRoute.js:12)
    in Route (at ViewTransitionRoute.js:10)
    in CSSTransitionRoute (at routes.js:74)
    in Switch (at routes.js:73)
    in Routes (created by Connect(Routes))
    in Connect(Routes) (at index.js:25)
    in div (at App.js:24)
    in div (at App.js:19)
    in App (created by Route)
    in Route (created by withRouter(App))
    in withRouter(App) (at index.js:24)
    in Route (at index.js:22)
    in Router (at index.js:21)
    in Provider (at index.js:20)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
function.console.(anonymous function) @ index.js:1
logCapturedError @ react-dom.development.js:14226
logError @ react-dom.development.js:14265
update.callback @ react-dom.development.js:14918
callCallback @ react-dom.development.js:10878
commitUpdateQueue @ react-dom.development.js:10922
commitLifeCycles @ react-dom.development.js:14396
commitAllLifeCycles @ react-dom.development.js:15462
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:15603
completeRoot @ react-dom.development.js:16618
performWorkOnRoot @ react-dom.development.js:16563
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
interactiveUpdates$1 @ react-dom.development.js:16719
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4532
VariableRegistry.js:50 Uncaught TypeError: Cannot read property 'replace' of undefined
    at VariableRegistry._this.renderEdge (VariableRegistry.js:50)
    at lodash.js:3563
    at lodash.js:4925
    at baseForOwn (lodash.js:3010)
    at lodash.js:4894
    at baseMap (lodash.js:3562)
    at map (lodash.js:9554)
    at VariableRegistry.renderEdges (VariableRegistry.js:77)
    at VariableRegistry.render (VariableRegistry.js:143)
    at finishClassComponent (react-dom.development.js:13193)
    at updateClassComponent (react-dom.development.js:13155)
    at beginWork (react-dom.development.js:13824)
    at performUnitOfWork (react-dom.development.js:15863)
    at workLoop (react-dom.development.js:15902)
    at renderRoot (react-dom.development.js:15942)
    at performWorkOnRoot (react-dom.development.js:16560)
    at performWork (react-dom.development.js:16482)
    at performSyncWork (react-dom.development.js:16454)
    at interactiveUpdates$1 (react-dom.development.js:16719)
    at interactiveUpdates (react-dom.development.js:2150)
    at dispatchInteractiveEvent (react-dom.development.js:4532)
VariableRegistry._this.renderEdge @ VariableRegistry.js:50
(anonymous) @ lodash.js:3563
(anonymous) @ lodash.js:4925
baseForOwn @ lodash.js:3010
(anonymous) @ lodash.js:4894
baseMap @ lodash.js:3562
map @ lodash.js:9554
renderEdges @ VariableRegistry.js:77
render @ VariableRegistry.js:143
finishClassComponent @ react-dom.development.js:13193
updateClassComponent @ react-dom.development.js:13155
beginWork @ react-dom.development.js:13824
performUnitOfWork @ react-dom.development.js:15863
workLoop @ react-dom.development.js:15902
renderRoot @ react-dom.development.js:15942
performWorkOnRoot @ react-dom.development.js:16560
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
interactiveUpdates$1 @ react-dom.development.js:16719
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4532
index.js:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-/HVuJpAuayjJW7D9fJCpJtUeRj9qM9o/BzKF9Hw7uTc='". Either the 'unsafe-inline' keyword, a hash ('sha256-gDC0EVcPe9MimCS3ZP14teSHr0GtEx+ggc0VQBfyvRI='), or a nonce ('nonce-...') is required to enable inline execution.

e.onload @ index.js:1
pe @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
```
Creating a new variable gives me a warning:
```
Warning: Failed prop type: The prop `variableType` is marked as required in `Validations`, but its value is `null`.
    in Validations (at Variable.js:104)
    in Variable (created by Connect(Variable))
    in Connect(Variable) (at Items.js:14)
    in div (at Items.js:13)
    in Transition (at Wipe.js:27)
    in FolderTransition (at Items.js:12)
    in div (created by TransitionGroup)
    in TransitionGroup (at Items.js:10)
    in div (at Items.js:8)
    in Items (created by ConnectedFieldArray)
    in ConnectedFieldArray (created by Connect(ConnectedFieldArray))
    in Connect(ConnectedFieldArray) (created by FieldArray)
    in FieldArray (at Variables.js:16)
    in Variables (created by Connect(Variables))
    in Connect(Variables) (at TypeEditor.js:118)
    in div (at TypeEditor.js:116)
    in Guided (created by Connect(Guided))
    in Connect(Guided) (at TypeEditor.js:115)
    in div (at TypeEditor.js:53)
    in TypeEditor (at Editor.js:23)
    in div (at Guided.js:66)
    in div (at Guided.js:65)
    in Guided (created by Connect(Guided))
    in Connect(Guided) (at Editor.js:22)
    in form (created by Form)
    in Form (at Editor.js:17)
    in Editor (created by Form(Editor))
    in Form(Editor) (created by Connect(Form(Editor)))
    in Connect(Form(Editor)) (created by ReduxForm)
    in ReduxForm (created by withHandlers(ReduxForm))
    in withHandlers(ReduxForm) (created by withState(withHandlers(ReduxForm)))
    in withState(withHandlers(ReduxForm)) (created by withProps(withState(withHandlers(ReduxForm))))
    in withProps(withState(withHandlers(ReduxForm))) (created by Connect(withProps(withState(withHandlers(ReduxForm)))))
    in Connect(withProps(withState(withHandlers(ReduxForm)))) (at EditType.js:90)
    in div (at Card.js:78)
    in div (at Card.js:77)
    in div (at Card.js:76)
    in Transition (at Card.js:45)
    in Card (at ProtocolCard.js:52)
    in ProtocolCard (at EditType.js:84)
    in EditType (created by Connect(EditType))
    in Connect(EditType) (at ShowRoute.js:9)
    in Route (at ShowRoute.js:8)
    in ShowRoute (at Protocol.js:189)
    in div (at Protocol.js:138)
    in Protocol (created by Connect(Protocol))
    in Connect(Protocol) (at ViewTransitionRoute.js:19)
    in Transition (created by CSSTransition)
    in CSSTransition (at ViewTransitionRoute.js:12)
    in Route (at ViewTransitionRoute.js:10)
    in CSSTransitionRoute (at routes.js:74)
    in Switch (at routes.js:73)
    in Routes (created by Connect(Routes))
    in Connect(Routes) (at index.js:25)
    in div (at App.js:24)
    in div (at App.js:19)
    in App (created by Route)
    in Route (created by withRouter(App))
    in withRouter(App) (at index.js:24)
    in Route (at index.js:22)
    in Router (at index.js:21)
    in Provider (at index.js:20)
```

After making some changes and going back in to the registry, I get this warning now, but I'm not sure which changes led to this:
```
Warning: Failed prop type: The prop `variableType` is marked as required in `Items`, but its value is `undefined`.
    in Items (created by ConnectedFieldArray)
    in ConnectedFieldArray (created by Connect(ConnectedFieldArray))
    in Connect(ConnectedFieldArray) (created by FieldArray)
    in FieldArray (at Options.js:84)
    in div (at Options.js:80)
    in Options (at Variable.js:97)
    in div (at Variable.js:72)
    in Guided (created by Connect(Guided))
    in Connect(Guided) (at Variable.js:71)
    in FormSection (at Variable.js:70)
    in div (at ExpandableItem.js:75)
    in div (at ExpandableItem.js:49)
    in ExpandablePrompt (at Variable.js:43)
    in Variable (created by Connect(Variable))
    in Connect(Variable) (at Items.js:14)
    in div (at Items.js:13)
    in Transition (at Wipe.js:27)
    in FolderTransition (at Items.js:12)
    in div (created by TransitionGroup)
    in TransitionGroup (at Items.js:10)
    in div (at Items.js:8)
    in Items (created by ConnectedFieldArray)
    in ConnectedFieldArray (created by Connect(ConnectedFieldArray))
    in Connect(ConnectedFieldArray) (created by FieldArray)
    in FieldArray (at Variables.js:16)
    in Variables (created by Connect(Variables))
    in Connect(Variables) (at TypeEditor.js:118)
    in div (at TypeEditor.js:116)
    in Guided (created by Connect(Guided))
    in Connect(Guided) (at TypeEditor.js:115)
    in div (at TypeEditor.js:53)
    in TypeEditor (at Editor.js:23)
    in div (at Guided.js:66)
    in div (at Guided.js:65)
    in Guided (created by Connect(Guided))
    in Connect(Guided) (at Editor.js:22)
    in form (created by Form)
    in Form (at Editor.js:17)
    in Editor (created by Form(Editor))
    in Form(Editor) (created by Connect(Form(Editor)))
    in Connect(Form(Editor)) (created by ReduxForm)
    in ReduxForm (created by withHandlers(ReduxForm))
    in withHandlers(ReduxForm) (created by withState(withHandlers(ReduxForm)))
    in withState(withHandlers(ReduxForm)) (created by withProps(withState(withHandlers(ReduxForm))))
    in withProps(withState(withHandlers(ReduxForm))) (created by Connect(withProps(withState(withHandlers(ReduxForm)))))
    in Connect(withProps(withState(withHandlers(ReduxForm)))) (at EditType.js:90)
    in div (at Card.js:78)
    in div (at Card.js:77)
    in div (at Card.js:76)
    in Transition (at Card.js:45)
    in Card (at ProtocolCard.js:52)
    in ProtocolCard (at EditType.js:84)
    in EditType (created by Connect(EditType))
    in Connect(EditType) (at ShowRoute.js:9)
    in Route (at ShowRoute.js:8)
    in ShowRoute (at Protocol.js:189)
    in div (at Protocol.js:138)
    in Protocol (created by Connect(Protocol))
    in Connect(Protocol) (at ViewTransitionRoute.js:19)
    in Transition (created by CSSTransition)
    in CSSTransition (at ViewTransitionRoute.js:12)
    in Route (at ViewTransitionRoute.js:10)
    in CSSTransitionRoute (at routes.js:74)
    in Switch (at routes.js:73)
    in Routes (created by Connect(Routes))
    in Connect(Routes) (at index.js:25)
    in div (at App.js:24)
    in div (at App.js:19)
    in App (created by Route)
    in Route (created by withRouter(App))
    in withRouter(App) (at index.js:24)
    in Route (at index.js:22)
    in Router (at index.js:21)
    in Provider (at index.js:20)
function.console.(anonymous function) @ index.js:1
printWarning @ checkPropTypes.js:19
checkPropTypes @ checkPropTypes.js:82
validatePropTypes @ react.development.js:1300
createElementWithValidation @ react.development.js:1388
React.createElement @ index.js:239
render @ ConnectedFieldArray.js:121
finishClassComponent @ react-dom.development.js:13193
updateClassComponent @ react-dom.development.js:13155
beginWork @ react-dom.development.js:13824
performUnitOfWork @ react-dom.development.js:15863
workLoop @ react-dom.development.js:15902
renderRoot @ react-dom.development.js:15942
performWorkOnRoot @ react-dom.development.js:16560
performWork @ react-dom.development.js:16482
performSyncWork @ react-dom.development.js:16454
interactiveUpdates$1 @ react-dom.development.js:16719
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4532
```
My understanding of [categorical vs ordinal](https://github.com/codaco/Network-Canvas/wiki/Variable-Types) is that both have options, but one is unordered, and the other an ordered scale.

**Comment by wwqrd** [comment]
Thanks! Lots of facepalms here.

> I'm not sure what is expected, but "Create New Node Type" and "Create New Edge Type" lead to a blank screen with a "Cancel" button.

Looks like I added a conditional render for when type is missing 🤦‍♂️ , should be a screen there 👍 

> If I edit the registry variables and then go back to the main page, I don't get a choice to "save" my protocol. I have to change one of the stages somehow to be able to save the protocol.

Nice spot, I'll add it to the list of saveable action types 👍 

> Creating a new protocol and then attempting to edit the registry gives me a blank screen and these errors, with no option to "cancel". Reload wasn't helping me much, I had to close the app and restart

👍

**Comment by wwqrd** [comment]
@rebeccamadsen @bryfox I've hopefully addressed all those issues, as well as adding a few more tests.

**Comment by bryfox** [comment]
This is looking great!

I notice a couple of things:

- variables will need `label`s eventually ([in addition to description](https://github.com/codaco/Network-Canvas/wiki/protocol.json#variable-registry)). But maybe that can wait until form editing is implemented; I think that's the only place they appear.
- In the generated registry, variables which cannot take options (e.g., number type) still get an "options: []" key/val in the registry. Not a big deal, but it feels like options should be omitted, or maybe set to null.

**Comment by wwqrd** [comment]
I can't figure out a way to remove parameters from redux-form after they've been set, so I'm using `null`, and then stripping them out when the form is saved to the protocol.

**Pull request merged**
